POST http://localhost:3000/heroes/2/superpowers
Content-Type: application/json

{
   "powerName":"Enhanced Speed",
   "description":"Over time Robin has maintained a very slim and light figure. He has honed this advantage in battle due to his training from Batman and can move very quickly across a very large field of play in a short amount of time."

}