POST http://localhost:3000/heroes
Content-Type: application/json

{
  "nickname" : "Robin",
  "realName" : "Timothy Drake",
  "originDescription" : "Batman's fight partner",
  "catchPhrase" : "hoooyeaaah"
}

